
package com.luis.enterprise;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EmployeeDB", targetNamespace = "http://enterprise.luis.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EmployeeDB {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setEmployee", targetNamespace = "http://enterprise.luis.com/", className = "com.luis.enterprise.SetEmployee")
    @ResponseWrapper(localName = "setEmployeeResponse", targetNamespace = "http://enterprise.luis.com/", className = "com.luis.enterprise.SetEmployeeResponse")
    @Action(input = "http://enterprise.luis.com/EmployeeDB/setEmployeeRequest", output = "http://enterprise.luis.com/EmployeeDB/setEmployeeResponse")
    public String setEmployee(
        @WebParam(name = "arg0", targetNamespace = "")
        Employee arg0);

}
