
package com.luis.enterprise;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EmployeeDBImplementService", targetNamespace = "http://enterprise.luis.com/", wsdlLocation = "http://localhost:1515/soap/employeedb?wsdl")
public class EmployeeDBImplementService
    extends Service
{

    private final static URL EMPLOYEEDBIMPLEMENTSERVICE_WSDL_LOCATION;
    private final static WebServiceException EMPLOYEEDBIMPLEMENTSERVICE_EXCEPTION;
    private final static QName EMPLOYEEDBIMPLEMENTSERVICE_QNAME = new QName("http://enterprise.luis.com/", "EmployeeDBImplementService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:1515/soap/employeedb?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EMPLOYEEDBIMPLEMENTSERVICE_WSDL_LOCATION = url;
        EMPLOYEEDBIMPLEMENTSERVICE_EXCEPTION = e;
    }

    public EmployeeDBImplementService() {
        super(__getWsdlLocation(), EMPLOYEEDBIMPLEMENTSERVICE_QNAME);
    }

    public EmployeeDBImplementService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EMPLOYEEDBIMPLEMENTSERVICE_QNAME, features);
    }

    public EmployeeDBImplementService(URL wsdlLocation) {
        super(wsdlLocation, EMPLOYEEDBIMPLEMENTSERVICE_QNAME);
    }

    public EmployeeDBImplementService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EMPLOYEEDBIMPLEMENTSERVICE_QNAME, features);
    }

    public EmployeeDBImplementService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EmployeeDBImplementService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EmployeeDB
     */
    @WebEndpoint(name = "EmployeeDBImplementPort")
    public EmployeeDB getEmployeeDBImplementPort() {
        return super.getPort(new QName("http://enterprise.luis.com/", "EmployeeDBImplementPort"), EmployeeDB.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EmployeeDB
     */
    @WebEndpoint(name = "EmployeeDBImplementPort")
    public EmployeeDB getEmployeeDBImplementPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://enterprise.luis.com/", "EmployeeDBImplementPort"), EmployeeDB.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EMPLOYEEDBIMPLEMENTSERVICE_EXCEPTION!= null) {
            throw EMPLOYEEDBIMPLEMENTSERVICE_EXCEPTION;
        }
        return EMPLOYEEDBIMPLEMENTSERVICE_WSDL_LOCATION;
    }

}
